# Docker Compose file (version post 3) for a personal DokuWiki instance
# Václav Brožík, 2024-03-07

# Used environment variables:
# - HTTP_PORT: Port for the DokuWiki instance (default: 40800)
# - BACKUP_DIR: Directory for backup files (default: current directory)
# - BACKUP_FILE_PREFIX: Prefix for backup files (default: dokuwiki_data_backup_)
# - BACKUP_FILE_SUFFIX: Suffix for backup files (default: .tbz)
# - BACKUP_RESTORE_DATE: Date in the backup file name to restore (default: current)

# Example usage:
# - To start the DokuWiki instance:
#     docker compose up -d
# - To create a backup in the current directory:
#     docker compose --profile backup run --rm backup
# - To restore from a backup from date 2024-03-07:
#     docker compose --profile restore run --rm -e BACKUP_RESTORE_DATE=20240307 restore

# version: "3.8"

services:

  dokuwiki:
    image: php:8-apache
    restart: unless-stopped
    networks:
      - frontend_network
    ports:
      - ${HTTP_PORT:-40800}:80
    volumes:
      - type: volume
        source: dokuwiki_data
        target: /var/www/html
    healthcheck:
      test: ["CMD", "curl", "-fsI", "http://localhost/doku.php"]
      interval: 5m
      timeout: 30s
      retries: 5
      start_period: 30s

  backup:
    # To be run manually: docker compose run --rm backup
    image: alpine
    restart: "no"
    network_mode: none
    volumes:
      - dokuwiki_data:/volume:ro
      - ${BACKUP_DIR:-./}:/backup
    command: >
      sh -c '
        backup_file_name=${BACKUP_FILE_PREFIX-dokuwiki_data_backup_}$$(date +%Y%m%d%H%M%S)${BACKUP_FILE_SUFFIX-.tbz}
        tar -cjf "/backup/$$backup_file_name" -C /volume . &&
          printf %s\\n "$$backup_file_name"
      '
    profiles:
      - backup

  restore:
    # To be run manually: docker compose run --rm restore
    image: alpine
    restart: "no"
    network_mode: none
    volumes:
      - type: volume
        source: dokuwiki_data
        target: /volume
        volume:
          nocopy: true
      - ${BACKUP_DIR:-./}:/backup:ro
    command: >
      tar -xjf /backup/${BACKUP_FILE_PREFIX-dokuwiki_data_backup_}${BACKUP_RESTORE_DATE:-current}${BACKUP_FILE_SUFFIX-.tbz} -C /volume
    profiles:
      - restore

networks:
  frontend_network:
    driver: bridge

volumes:
  dokuwiki_data:
    driver: local
